name: Build & Release v2rayA
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The tag to release"
        required: true
jobs:
  Build_v2rayA_Web:
    uses: ./.github/workflows/_build_web.yml
    with:
      upload_archive: true

  Compute_Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prep.outputs.VERSION }}
    steps:
      - name: Compute Version
        id: prep
        run: |
          tag=${{ inputs.tag }}
          version=$(echo $tag | sed 's/v//g')
          echo "VERSION=$version" >> $GITHUB_OUTPUT

  Build_v2rayA_Binaries:
    needs: [Build_v2rayA_Web, Compute_Version]
    uses: ./.github/workflows/_build_binaries.yml
    with:
      version: ${{ needs.Compute_Version.outputs.version }}

  Build_Windows_Installers:
    needs: [Build_v2rayA_Binaries, Compute_Version]
    uses: ./.github/workflows/_build_windows_installer.yml
    with:
      version: ${{ needs.Compute_Version.outputs.version }}

  Build_Linux_Packages:
    needs: [Build_v2rayA_Binaries, Compute_Version]
    uses: ./.github/workflows/_build_linux_packages.yml
    with:
      version: ${{ needs.Compute_Version.outputs.version }}

  GitHub_Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # Required to create releases or push tags/code
      pull-requests: write      # Required to comment or manage PRs
      checks: write             # Required for status checks / security scans
    needs:
      [Build_v2rayA_Binaries, Build_Windows_Installers, Build_Linux_Packages]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check Version
        id: prep
        env:
          REF: ${{ inputs.tag }}
        run: |
          tag=${{ inputs.tag }}
          version=$(echo $tag | sed 's/v//g')
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: builds/
      - name: Move Files to Release Directory
        shell: bash
        run: |
          mkdir -p release
          for file in $(ls builds | grep -E "^installer|^v2raya"); do
            mv builds/$file/$file release/
          done
          mv builds/web.tar.gz/web.tar.gz release/
          for file in $(ls release); do
            sha256sum release/$file | awk '{print $1}' > release/$file.sha256.txt
          done
          ls -l release/
      - name: Compress Web Files
        shell: pwsh
        run: |
          Compress-Archive -Path ./builds/web/* -DestinationPath ./web.zip
          ((Get-FileHash ./web.zip).hash).ToLower() > web.zip.sha256.txt
          Move-Item ./web.zip ./release/web.zip
          Move-Item ./web.zip.sha256.txt ./release/web.zip.sha256.txt
      - name: Upload Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          Latest_Releases=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/v2rayA/v2rayA/releases/latest | jq -r '.tag_name')
          Latest_tag=v${{ steps.prep.outputs.VERSION }}
          if [ "$Latest_Releases" != "$Latest_tag" ]; then
            gh release create "v${{ steps.prep.outputs.VERSION }}" -t "v${{ steps.prep.outputs.VERSION }}" --generate-notes
          fi
          gh release upload "v${{ steps.prep.outputs.VERSION }}" release/*
  
  Release_Docker_Images:
    runs-on: ubuntu-latest
    needs: [GitHub_Release]
    permissions:
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check Version
        id: prep
        run: |
          tag=${{ inputs.tag }}
          version=$(echo $tag | sed 's/v//g')
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV
          IMAGE="mzz2017/v2raya"
          echo image=${IMAGE} >> $GITHUB_OUTPUT
          echo tag=${{ inputs.tag }} >> $GITHUB_OUTPUT
          sed -i "s|Realv2rayAVersion|$version|g" install/docker/docker_helper.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to GitHub container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Convert repository owner to lowercase
        run: |
          echo "LOWERCASE_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >>${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: install/docker/Dockerfile.Action
          platforms: linux/arm,linux/arm64,linux/amd64,linux/riscv64
          push: true
          tags: |
            ghcr.io/${{ env.LOWERCASE_REPOSITORY_OWNER }}/v2raya:${{ steps.prep.outputs.tag }}
            ghcr.io/${{ env.LOWERCASE_REPOSITORY_OWNER }}/v2raya:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

